### ISSUE TITLE
create where are my ref sites diagnostics

### ISSUE THREAD

**Issue by fawda123** [SCCWRP/CSCI#6]
slides 1, 3, and 6 as standard (add selected, non-selected jitter on slide 3), slides 2 and 4 as backup, create summary stats (z-score maybe) of weighted average of env variable value minus ref site values, weights as proximity, also do for PCA plots in ordination space.

**Comment by fawda123** [comment]
@raphaelmazor does this sum it up?

**Comment by raphaelmazor** [comment]
I think so. I’m curious to see how a scoring system works out…

-------------------------------------------------------------------
Raphael Mazor
Senior Scientist
Southern California Coastal Water Research Project
3535 Harbor Blvd, Suite 110
Costa Mesa, CA 92626

Tel: 714-755-3235
Fax: 714-755-3299

**Comment by fawda123** [comment]
6e8ab0a4da2e285f7a2c315b085c69544f4d9da9 https://sccwrp.github.io/CSCI/reference/refprox.html
