### ISSUE TITLE
MMI calculations change when additional sites are added to the analysis.

### ISSUE THREAD

**Issue by adamkc** [SCCWRP/CSCI#7]
I'm not sure what to make of this problem. Basically adding an extra site to a CSCI function call drastically changes the MMI Scores and consequently CSCI Scores.  The OoverE remain unchanged. The minimal reproducible example could look something like this:
```
data(bugs_stations)
CSCI(bugs_stations[[1]] %>%
       subset(StationCode=="Site2"), bugs_stations[[2]])$core
CSCI(bugs_stations[[1]] %>%
       subset(StationCode=="Site2"|
                StationCode=="Site3"), bugs_stations[[2]])$core
CSCI(bugs_stations[[1]] %>%
       subset(StationCode=="Site3"), bugs_stations[[2]])$core
```
The I can't really tell if the above code actually reproduces the problem.  In my own data file I have ~20 sites that when run together produce reasonable results but when I add another site ("Site3") that has multiple samples things get really weird at some sites while others remain unchanged.  In my own data files the results look something like this (with the Call1-3 coinciding with the above code):

                      Call1_MMI      Call2_MMI       Call3_MMI
       Site2           0.8840655     0.3330822
       Site3.1                       0.5329718       0.6794666
       Site3.2                       1.2256650       1.2256650
       Site3.3                       1.2305833       0.5329718

What do you make of this? Do you need my data files to troubleshoot?  My data is from CEDEN, Site 2 is "111MJE006" and Site 3 is "111WE1071".  

Let me know what I can do to help track this down.  It would have caused major issues for us if hadn't noticed the numbers changing.

**Comment by fawda123** [comment]
This was an issue with `StationCode` and `SampleID` as factors.  It's been fixed by coercing these fields to character string within the `CSCI()` function.

42c2a5602a545aebcb7e748b91d0bfe307ca5d45
